### ISSUE TITLE
Two different FAQ's

### ISSUE THREAD

**Issue by keunes** [AntennaPod/antennapod.github.io#12]
@mfietz I saw you created a new FAQ page, whilst there already is an FAQ in the wiki. i think your work is a bit better in approach towards content and in presentation, but I don't think it's a good idea to keep two FAQ's (it's more work to keep more versions up to date and confusing for users).
So I'm wondering why you started a new FAQ rather than updating the wiki-one.
Do you think there's a way to put your content in the wiki-page and somehow get it to display in a nicer way? (so that there's only one content-source)

**Comment by mfietz** [comment]
Couldn't use the old FAQ in the app, because the wiki is not even accessible from mobile devices.
I basically started from scratch for the new version, because answers in the old version are just too long and the real *frequently* asked questions are missing.
Once I have more time to expand the new version, the wiki page will probably get deleted. Right now, it is pretty useless.

**Comment by keunes** [comment]
And thanks very much :S

> the wiki is not even accessible from mobile devices
That's why I asked if you think it's possible to take the raw wiki data (taking your content) and presenting it in a different form.

> answers in the old version are just too long

They could be made short, or you could replace them with your content...

> the real frequently asked questions are missing

Frankly, the questions I put in the wiki-FAQ I think do address questions that come up frequently on GitHub or in the Google group. Define _real_.

**Comment by mfietz** [comment]
Don't really see the point of this discussion. 

> it's more work to keep more versions up to date and confusing for users

I will only keep one version up to date. Problem solved.
I also don't think keeping the wiki page for now will confuse any users. It is pretty well hidden and I would be rather surprised if anyone stumbles upon it.

**Comment by keunes** [comment]
This could barely be called a discussion, but hey, feel free to call it whatever you want.
(Why I asked why you did not update the FAQ but rather started sth new: Call me sensitive - but it feels a bit annoying if your initiative is being ignored, and I got a bit more annoyed when I felt my well-intended attempts rücksichtslos were being labeled as 'useless'.)

Returning to the only real issue here, why I asked if it's possible to put the FAQ content in the wiki and 'pipe' it into a different form/page:
- keep all knowledge together (the 'knowledge base' should be the wiki, IMHO, rather than having a wiki, a seperate FAQ, etc)
- keeping the 'knowledge base' accessible for easy contributions (i.e. a wiki style)
- being able to integrate (parts of) the wiki into the regular website (in a later stage)

**Comment by mfietz** [comment]
> the 'knowledge base' should be the wiki, IMHO, rather than having a wiki, a seperate FAQ, etc
> keeping the 'knowledge base' accessible for easy contributions (i.e. a wiki style)

Using the wiki would only be an advantage if more people would be contributing. With only 1-2 people, I don't really see the advantage of using the wiki for this. I'd rather create the page that is used in the app directly than parsing the wiki page and creating it dynamically (someone would have to implement that parser and run it periodically).
Also, the new knowledge base is still at an early stage. I only really uploaded it this early so that it could be added in the apps settings. Currently, it is only "good enough". Eventually, I will probably come up with a simple textfile format that will generate the knowledge base(s) to support translations.

> being able to integrate (parts of) the wiki into the regular website (in a later stage)

Or the website could just link to the new knowledge base.
I doubt that the wiki page can be integrated easily into the website. Probably a lot of copy-n-paste.

> being labeled as 'useless'

I called the wiki page useless because it currently has no use for me.
There is not much contributing going on (except now and again a question I answered somewhere else is copy and pasted), it is almost impossible for any users to find it (find github, open wiki, expand pages...) and github does support using the wiki pages on mobile devices, i.e. direct use in the app won't work.
