### ISSUE TITLE
Linkcheck fails

### ISSUE THREAD

**Issue by Rotzbua** [AntennaPod/antennapod.github.io#282]
**Short description**: 

Linkcheck fails on every PR.
Even if there is no new link.

**Possible solutions**: 

* Linkcheck should just check new links.
* Run linkcheck just periodically.

**Comment by keunes** [comment]
We decided to make the check fail so that broken links won't be overlooked:
https://github.com/AntennaPod/antennapod.github.io/pull/256#discussion_r1285389103

I personally think we should also check old links, and running linkcheck only periodically would be fine if done regularly, but given the level of activity, running it at each PR probably is good enough.
